### ISSUE TITLE
Where can cad-cap datasets be obtained?

### ISSUE THREAD

**Issue by sunlight002** [Guo-Xiaoqing/SSL_WCE#5]

**Comment by Guo-Xiaoqing** [comment]
Can you give me your email address, and then I will share the dataset with you.

**Comment by Guo-Xiaoqing** [comment]
> _No description provided._


Can you give me your email address, and then I will share the dataset with you?

**Comment by sunlight002** [comment]
Thank you very much！ 1053323549@qq.com
